return {}

-- old version
-- return {
--   {
--     'zbirenbaum/copilot.lua',
--     cmd = 'Copilot',
--     build = ':Copilot auth',
--     event = 'BufReadPost',
--     opts = {
--       auto_trigger = true,
--       suggestion = {
--         enabled = false,
--       },
--       panel = { enabled = false },
--       filetypes = {
--         markdown = true,
--         help = true,
--       },
--     },
--   },
--   { 'giuxtaposition/blink-cmp-copilot' },
--   -- {
--   --   'saghen/blink.cmp',
--   --   optional = true,
--   --   dependencies = { 'giuxtaposition/blink-cmp-copilot' },
--   --   opts = {
--   --     sources = {
--   --       providers = {
--   --         copilot = {
--   --           name = 'copilot',
--   --           module = 'blink-cmp-copilot',
--   --           kind = 'Copilot',
--   --           score_offset = 100,
--   --           async = true,
--   --         },
--   --       },
--   --     },
--   --   },
--   -- },
--   --
--   {
--     'CopilotC-Nvim/CopilotChat.nvim',
--     dependencies = {
--       { 'zbirenbaum/copilot.lua' }, -- or zbirenbaum/copilot.lua
--       { 'nvim-lua/plenary.nvim', branch = 'master' }, -- for curl, log and async functions
--     },
--     build = 'make tiktoken', -- Only on MacOS or Linux
--     opts = {
--       -- See Configuration section for options
--     },
--     -- See Commands section for default commands if you want to lazy load on them
--   },
-- }

-- return {
--   {
--     'zbirenbaum/copilot.lua',
--     cmd = 'Copilot',
--     event = 'InsertEnter',
--     opts = {
--       suggestion = { enabled = false },
--       panel = { enabled = false },
--       filetypes = {
--         markdown = true,
--         help = true,
--       },
--     },
--   },
--   {
--     'CopilotC-Nvim/CopilotChat.nvim',
--     dependencies = {
--       { 'zbirenbaum/copilot.lua' }, -- or zbirenbaum/copilot.lua
--       { 'nvim-lua/plenary.nvim', branch = 'master' }, -- for curl, log and async functions
--     },
--     build = 'make tiktoken', -- Only on MacOS or Linux
--     opts = {
--       -- See Configuration section for options
--     },
--     -- See Commands section for default commands if you want to lazy load on them
--   },
-- }
