return {}
-- return {
--   'jghauser/papis.nvim',
--   dependencies = {
--     'kkharji/sqlite.lua',
--     'MunifTanjim/nui.nvim',
--     'pysan3/pathlib.nvim',
--     'nvim-neotest/nvim-nio',
--     -- if not already installed, you may also want:
--     -- "hrsh7th/nvim-cmp",
--
--     -- Choose one of the following two if not already installed:
--     -- "ibhagwan/fzf-lua",
--     -- "folke/snacks.nvim",
--   },
--   config = function()
--     require('papis').setup {
--       -- Your configuration goes here
--       enable_keymaps = true,
--     }
--   end,
-- }
